// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-heritages.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient } from "npm:@supabase/supabase-js@^2.105.3";
import { z } from "npm:zod@^3.25.76";
var list_heritages_default = defineTool({
  name: "list_heritages",
  title: "List Vietnamese heritages",
  description: "List Vietnamese cultural and natural heritage entries from the H\u1ED3n Vi\u1EC7t database (title, slug, region, UNESCO type, year, short description). Optional filter by region (bac/trung/nam) or unesco_type.",
  inputSchema: {
    region: z.enum(["bac", "trung", "nam"]).optional().describe("Filter by region: bac (North), trung (Central), nam (South)."),
    unesco_type: z.string().optional().describe("Filter by UNESCO type substring, e.g. 'v\u1EADt th\u1EC3', 'phi v\u1EADt th\u1EC3', 'thi\xEAn nhi\xEAn'."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ region, unesco_type, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false } }
    );
    let q = supabase.from("heritages").select("slug,title,subtitle,region,unesco_type,year,short_desc,origin").order("display_order", { ascending: true }).limit(limit ?? 50);
    if (region) q = q.eq("region", region);
    if (unesco_type) q = q.ilike("unesco_type", `%${unesco_type}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-heritage.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.105.3";
import { z as z2 } from "npm:zod@^3.25.76";
var get_heritage_default = defineTool2({
  name: "get_heritage",
  title: "Get heritage detail",
  description: "Fetch the full detail of a single Vietnamese heritage entry by slug \u2014 including history, characteristics, origin, preservation status, references, and long description.",
  inputSchema: {
    slug: z2.string().min(1).describe("Heritage slug, e.g. 'hoi-an', 'nha-nhac-cung-dinh-hue'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false } }
    );
    const { data, error } = await supabase.from("heritages").select("*").eq("slug", slug).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No heritage found with slug '${slug}'.` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { heritage: data }
    };
  }
});

// src/lib/mcp/tools/list-regions.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.105.3";
var list_regions_default = defineTool3({
  name: "list_regions",
  title: "List Vietnamese cultural regions",
  description: "List the three cultural regions of Vietnam (North / Central / South) with summaries.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false } }
    );
    const { data, error } = await supabase.from("regions").select("slug,code,name,sub,tagline,intro,geography").order("display_order", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-region.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.105.3";
import { z as z3 } from "npm:zod@^3.25.76";
var get_region_default = defineTool4({
  name: "get_region",
  title: "Get region detail",
  description: "Fetch the full detail of one Vietnamese cultural region by slug \u2014 geography, history, tangible & intangible heritages, cuisine, landmarks.",
  inputSchema: {
    slug: z3.string().min(1).describe("Region slug, e.g. 'mien-bac', 'mien-trung', 'mien-nam'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = createClient4(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false } }
    );
    const { data, error } = await supabase.from("regions").select("*").eq("slug", slug).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No region found with slug '${slug}'.` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { region: data }
    };
  }
});

// src/lib/mcp/tools/search-heritages.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.105.3";
import { z as z4 } from "npm:zod@^3.25.76";
var search_heritages_default = defineTool5({
  name: "search_heritages",
  title: "Search heritages",
  description: "Search Vietnamese heritages by keyword across title, subtitle, and short description (case-insensitive).",
  inputSchema: {
    query: z4.string().min(1).describe("Free-text keyword, e.g. 'ca tr\xF9', 'H\u1ED9i An', 'Ch\u0103m'."),
    limit: z4.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const supabase = createClient5(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false } }
    );
    const like = `%${query}%`;
    const { data, error } = await supabase.from("heritages").select("slug,title,subtitle,region,unesco_type,year,short_desc").or(`title.ilike.${like},subtitle.ilike.${like},short_desc.ilike.${like}`).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { items: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "hon-viet-mcp",
  title: "H\u1ED3n Vi\u1EC7t \u2014 Vietnamese Heritage",
  version: "0.1.0",
  instructions: "Tools for the H\u1ED3n Vi\u1EC7t app \u2014 Vietnamese cultural and natural heritage, history, and the three cultural regions (North / Central / South). Use `list_heritages` or `search_heritages` to discover entries, then `get_heritage` for full detail. Use `list_regions` and `get_region` for region-level context (geography, tangible/intangible heritages, cuisine, landmarks). All data is public.",
  tools: [list_heritages_default, search_heritages_default, get_heritage_default, list_regions_default, get_region_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
