
UPDATE public.regions
SET
  cuisine = '["Phở Hà Nội","Bún chả Hàng Mành","Bánh cuốn Thanh Trì","Chả cá Lã Vọng","Cốm làng Vòng","Bún thang Hà Nội","Bánh tôm Hồ Tây"]'::jsonb,
  intro = 'Miền Bắc là vùng đất tổ của dân tộc Việt, nơi các vua Hùng dựng nước Văn Lang, nơi trống đồng Đông Sơn ngân vang và Thăng Long ngàn năm văn hiến trở thành biểu tượng của quốc gia. Bốn nghìn năm dòng chảy lịch sử đã in dấu trên từng viên gạch phố cổ, từng triền núi Hoàng Liên, từng làn điệu Quan họ — Ca trù, kết tinh trong hình ảnh ''cây đa — bến nước — sân đình'' đậm tính cộng đồng làng xã đồng bằng sông Hồng.',
  landmarks = '[
    {"name":"Hồ Hoàn Kiếm & Phố cổ Hà Nội","province":"Hà Nội","type":"Đô thị cổ","image":"hanoi-old-quarter","highlight":"Truyền thuyết Lê Lợi trả gươm cho Rùa Vàng — trái tim ngàn năm văn hiến với Tháp Rùa, cầu Thê Húc đỏ son, đền Ngọc Sơn và 36 phố Hàng của các làng nghề kinh kỳ."},
    {"name":"Khu di tích Hoàng thành Thăng Long","province":"Hà Nội","type":"Kinh thành cổ","image":"hoang-thanh-thang-long","highlight":"Trung tâm quyền lực Đại Việt suốt 13 thế kỷ với điện Kính Thiên, Đoan Môn, Hậu Lâu — Di sản Văn hoá Thế giới UNESCO 2010."},
    {"name":"Văn Miếu — Quốc Tử Giám","province":"Hà Nội","type":"Di tích văn hoá","image":"van-mieu","highlight":"Trường đại học đầu tiên của Việt Nam (1070) với 82 bia tiến sĩ khắc tên 1.307 vị hiền tài — Ký ức Thế giới UNESCO."},
    {"name":"Chùa Một Cột (Diên Hựu)","province":"Hà Nội","type":"Kiến trúc Phật giáo","image":"chua-mot-cot","highlight":"Đoá sen đá vươn lên từ hồ Linh Chiểu — biểu tượng kiến trúc thanh tao bậc nhất thời Lý (1049)."},
    {"name":"Thành Cổ Loa","province":"Đông Anh — Hà Nội","type":"Thành cổ","image":"co-loa","highlight":"Toà thành ốc ba vòng của An Dương Vương — kinh đô Âu Lạc cổ và công trình quân sự lớn nhất Đông Nam Á thời cổ đại."},
    {"name":"Vịnh Hạ Long","province":"Quảng Ninh","type":"Biển đảo","image":"halong-bay","highlight":"Truyền thuyết Rồng Mẹ phun ngọc hoá thành ngàn đảo đá vôi — kỳ quan thiên nhiên thế giới UNESCO 1994 & 2000."},
    {"name":"Sa Pa & đỉnh Fansipan","province":"Lào Cai","type":"Núi","image":"sapa-fansipan","highlight":"Nóc nhà Đông Dương 3.143m trên dãy Hoàng Liên Sơn, ruộng bậc thang Mường Hoa, chợ tình bản Cát Cát — Tả Van."},
    {"name":"Quần thể Tràng An","province":"Ninh Bình","type":"Danh thắng","image":"trang-an","highlight":"''Trận đồ bát quái bằng nước'' với hang xuyên thuỷ, cố đô Hoa Lư và chùa Bái Đính — di sản hỗn hợp duy nhất Đông Nam Á."},
    {"name":"Tam Cốc — Bích Động","province":"Ninh Bình","type":"Danh thắng","image":"tam-coc","highlight":"Ba hang xuyên núi trên dòng Ngô Đồng, hai bờ lúa chín vàng tháng Năm — ''Vịnh Hạ Long trên cạn'' thơ mộng."},
    {"name":"Hồ Ba Bể","province":"Bắc Kạn","type":"Sông hồ","image":"ba-be-lake","highlight":"Một trong 20 hồ nước ngọt trên núi đá vôi lớn nhất thế giới, hình thành từ đứt gãy địa chất 200 triệu năm trước."},
    {"name":"Cao nguyên đá Đồng Văn","province":"Hà Giang","type":"Danh thắng","image":"ha-giang","highlight":"Công viên địa chất toàn cầu UNESCO với đèo Mã Pí Lèng, sông Nho Quế xanh ngọc và hoa tam giác mạch."},
    {"name":"Mù Cang Chải","province":"Yên Bái","type":"Danh thắng","image":"mu-cang-chai","highlight":"Ruộng bậc thang vàng óng mùa lúa chín tháng Chín — kiệt tác canh tác trên độ dốc 70° của người H''Mông."},
    {"name":"Chùa Hương — Hương Sơn","province":"Hà Nội","type":"Danh thắng tâm linh","image":"chua-huong","highlight":"Quần thể Hương Sơn với suối Yến và động Hương Tích — ''Nam thiên đệ nhất động'' do chúa Trịnh Sâm đề tự."}
  ]'::jsonb,
  landmarks_note = 'Từ phố cổ ngàn năm Thăng Long, kinh thành Hoàng thành — Cổ Loa đến biển ngọc Hạ Long, ruộng bậc thang Tây Bắc và cao nguyên đá Hà Giang — miền Bắc là bản đồ giao hoà giữa kinh đô cổ, núi sông kỳ vĩ và những công trình tâm linh nghìn tuổi.',
  intangible = '[
    {"name":"Dân ca Quan họ Bắc Ninh","type":"Âm nhạc dân gian","origin":"49 làng Quan họ gốc — Bắc Ninh & Bắc Giang","era":"Thế kỷ XIII","unesco":"2009","desc":"Lối hát đối đáp giao duyên giữa liền anh — liền chị với hơn 200 làn điệu cổ, tục kết chạ và lề lối ''hát canh — hát hội — hát thờ'' đặc sắc."},
    {"name":"Ca trù","type":"Nghệ thuật hát thơ bác học","origin":"Đồng bằng Bắc Bộ — Hà Nội, Hải Dương, Hải Phòng","era":"Thế kỷ XI","unesco":"2009 (cần bảo vệ khẩn cấp)","desc":"Nghệ thuật hát thơ tinh tế của giới nho sĩ trong giáo phường, hoà quyện phách, đàn đáy và trống chầu — di sản đang được nỗ lực khôi phục."},
    {"name":"Tín ngưỡng thờ Mẫu Tam phủ","type":"Tín ngưỡng bản địa","origin":"Phủ Dầy — Nam Định, đền Sòng — Thanh Hoá","era":"Thế kỷ XVI","unesco":"2016","desc":"Tín ngưỡng thờ Mẹ với nghi lễ hầu đồng, hệ thống 36 giá đồng và âm nhạc hát văn — kết tinh tinh thần ''Mẹ thiên nhiên'' của người Việt."},
    {"name":"Hội Gióng đền Phù Đổng & đền Sóc","type":"Lễ hội truyền thống","origin":"Gia Lâm & Sóc Sơn — Hà Nội","era":"Hàng nghìn năm","unesco":"2010","desc":"Tái hiện huyền thoại Thánh Gióng đánh giặc Ân — một trong Tứ bất tử. Đền Sóc (mùng 6–8 tháng Giêng) nổi tiếng nghi lễ cướp hoa tre; đền Phù Đổng (mùng 7–9 tháng Tư) là ''vở kịch thực cảnh dân gian'' với các điệu múa Ông Hiệu Cờ — Trống — Chiêng."},
    {"name":"Tín ngưỡng thờ Hùng Vương","type":"Tín ngưỡng tổ tiên","origin":"Đền Hùng — núi Nghĩa Lĩnh, Phú Thọ","era":"Hàng nghìn năm","unesco":"2012","desc":"Đỉnh điểm vào ngày Giỗ Tổ 10/3 Âm lịch với nghi thức rước kiệu, lễ dâng hương, hội thi gói bánh chưng, giã bánh giầy — thể hiện đạo lý ''uống nước nhớ nguồn''."},
    {"name":"Hát Xoan Phú Thọ","type":"Hát nghi lễ cửa đình","origin":"Bốn phường Xoan gốc — Phú Thọ","era":"Thời Hùng Vương (truyền thuyết)","unesco":"2011 (khẩn cấp) → 2017 (đại diện)","desc":"Một buổi hát Xoan gồm 3 chặng: Hát nghi lễ cầu chúc — Hát quả cách ngâm tích sử — Hát hội giao duyên giữa đào và kép. Di sản đầu tiên được rút khỏi danh sách bảo vệ khẩn cấp của UNESCO."},
    {"name":"Thực hành Then của người Tày, Nùng, Thái","type":"Diễn xướng tâm linh","origin":"Lạng Sơn, Cao Bằng, Tuyên Quang, Bắc Kạn","era":"Hàng trăm năm","unesco":"2019","desc":"''Then'' nghĩa là ''Thiên'' (Trời). Thầy Then vừa đàn tính, vừa lắc xóc nhạc, vừa hát múa — cầu nối giữa con người, tổ tiên và thần linh để cầu an, giải hạn, cầu mùa."},
    {"name":"Nghệ thuật Xoè Thái","type":"Múa cộng đồng","origin":"Tây Bắc — Yên Bái, Sơn La, Điện Biên, Lai Châu","era":"Hàng trăm năm","unesco":"2021","desc":"Sáu điệu xoè cổ, tiêu biểu là ''Khắm khen'' (nắm tay vòng tròn — đoàn kết) và ''Đổn tấu'' (bước tiến lùi — vững bước qua thăng trầm). ''Không xoè không vui, không xoè trai gái không thành đôi.''"},
    {"name":"Nghi lễ và trò chơi Kéo co","type":"Trò chơi nghi lễ","origin":"Hữu Chấp — Bắc Ninh, đền Trấn Vũ — Hà Nội","era":"Hàng trăm năm","unesco":"2015 (đa quốc gia)","desc":"Cầu mưa thuận gió hoà, mùa màng tươi tốt. Độc đáo nhất là ''Kéo co ngồi'' đền Trấn Vũ: người chơi ngồi bệt, gót chân đạp hố cát, luồn tay qua nách kéo dây song — mô phỏng giữ phai giữ đập của cư dân lúa nước."}
  ]'::jsonb,
  intangible_note = 'Văn hoá phi vật thể Bắc Bộ gắn liền với làng xã đồng bằng sông Hồng và bản mường vùng cao, mang đậm tính cộng đồng, nghi lễ nông nghiệp lúa nước, tín ngưỡng tổ tiên và sự đa sắc tộc của các dân tộc thiểu số Tày — Nùng — Thái — H''Mông.'
WHERE slug = 'bac';
